### ISSUE TITLE
Can we support Pow with the new workflow?

### ISSUE THREAD

**Issue by ghost** [half-pipe/half-pipe#48]
Since assets are built in dev through `grunt server`, Pow users will have some difficulty.

My suggestion is to have the Rack middleware there for anyone who might need it. I know there are some performance concerns but it may be the only solution for Pow users.

**Comment by joefiorini** [comment]
Unfortunately, I do not see using Rack middleware as an option. When we were using Rack in development we had some configuration in Ruby and some in Grunt. This led to a lot of confusion, and not actually using Grunt to it's potential.

An eventual workaround for this might be to support pow-based workflows in the [`grunt-rails-server` plugin](https://github.com/joefiorini/grunt-rails-server). I've created joefiorini/grunt-rails-server#1 to discuss this over there. Once that is working, you should be able to change your proxy config to point to your pow hostname. 

You'll still need  to use `localhost:3000` though for developing on assets, as that's where the preview server runs. Not much we can do about that until pow supports node apps.
