### ISSUE TITLE
Performance stats in README?

### ISSUE THREAD

**Issue by carols10cents** [half-pipe/half-pipe#49]
Hi, I've been using a grunt-based workflow in a non-rails project and it's made me really frustrated with the time the asset pipeline takes in my rails projects.

I'm probably going to try out half-pipe soon, but one thing that would be awesome to know before I go down this path is a comparison of `rake assets:precompile` vs compiling with grunt.

Perhaps link to a sample project with a few assets configured in one branch to use the asset pipeline and on another branch to use half-pipe (this would be great as documentation in general too!) and then report how long each takes on a particular machine with a particular version of ruby?

**Comment by joefiorini** [comment]
Hey, thanks for the request. At the moment my primary concern is documentation, so I would not be able to get to this for awhile. If you want to fork & create a perf branch and include a couple projects with benchmark scripts I would happily include the results in the README.
