### ISSUE TITLE
Asset Versioning

### ISSUE THREAD

**Issue by smith** [half-pipe/half-pipe#54]
Is there currently a way to generate assets for production with a hash so it looks like application-ceff30f190a9c5dbb68b141c610b3f16.js? It looks like right now it just does application.js which loses all of the caching advantages. Is this something that's not yet implemented or is there something else I need to do to make it work?

**Comment by joefiorini** [comment]
I have not implemented it, but I do plan on adding support for [`grunt-rev`](https://gist.github.com/joefiorini/0c71266b9483425b3fb0) soon. In the meantime, you can add it to your own Gruntfile and try it out. I suspect half-pipe's `javascript_include_tag` helper will need to be updated to support hash-based lookup. I would happily accept a PR for this.

**Comment by joefiorini** [comment]
I'm going to close this for now. If you implement this please feel free to send a PR. If not, we'll track the progress in a separate issue when I get some time to work on it.

**Comment by jwietelmann** [comment]
Has this been added yet?
