### ISSUE TITLE
Lower minimum rails requirement

### ISSUE THREAD

**Issue by AlecRust** [half-pipe/half-pipe#70]
I'm working on an app that runs rails 3.2.16. I'd like to use the latest half-pipe 0.3.0 but it has a [minimum requirement](https://github.com/d-i/half-pipe/blob/master/half-pipe.gemspec#L21) of rails 4.

I forked the gem, lowered the minimum version requirement, repackaged it and installed it in my app, but am getting this error when running `bundle exec rails g half_pipe:install` (excuse screenshot):

![screenshot 2014-02-08 17 55 10](https://f.cloud.github.com/assets/247634/2118714/8cd3fbc2-911a-11e3-90b2-430713d8b452.png)

(we're using [rbenv](https://github.com/sstephenson/rbenv) in this application)

I'm wondering how many changes are required to get this to work in rails 3. The upgrade from 3 to 4 is a substantial one, I imagine there are still quite a few applications that could benefit from half-pipe that don't use rails 4.

**Comment by joefiorini** [comment]
Sorry it's taken me so long to reply. The main issue here is that Rails 4 made it possible to configure the base paths that the asset helpers use. This makes supporting half-pipe's custom directory structure extremely simple.

Prior to discovering this feature, I had rewritten each of these helpers to generate the correct URLs. I think a solution here would be to bring that code back and separate the railtie into configuration for Rails 3 vs. Rails 4, similar to how `rails-api` switches middleware stacks based on Rails version.

If this is still an issue for you I'd be happy to accept a PR for this. Please let me know of you have additional questions.

**Comment by AlecRust** [comment]
It's no longer an issue for me actually, the application in question has been upgraded to Rails 4. Many thanks for your response though!

**Comment by joefiorini** [comment]
Great, thanks for following up. I'm going to go ahead and close this. If anyone else runs into it in the future, please open a new issue.
