### ISSUE TITLE
initial grunt requirejs:public fails

### ISSUE THREAD

**Issue by ballPointPenguin** [half-pipe/half-pipe#71]
Steps to recreate:
1. create new Rails 4.0 app
2. add half-pipe to Gemfile and run bundle install
3. run rails g half_pipe:install

output:

> Running "requirejs:public" (requirejs) task
> >> Error: ENOENT, no such file or directory
> >> '/Users/brosas/dev/half-pipe-test/bower_components/jquery/jquery.js'
> >> In module tree:
> >>     half-pipe-test
> Warning: RequireJS failed. Use --force to continue.
> 
> Aborted due to warnings.

looking inside of bower_components/jquery:

> bower_components/jquery
> ├── MIT-LICENSE.txt
> ├── bower.json
> ├── dist
> │   ├── jquery.js
> │   ├── jquery.min.js
> │   └── jquery.min.map
> └── src
>     ├── ...
>     ├── jquery.js
>     ├──...

**Comment by joefiorini** [comment]
Thanks for the PR on this!
