### ISSUE TITLE
Bug? Install broke my Rails app completely.

### ISSUE THREAD

**Issue by cranesandcaff** [half-pipe/half-pipe#75]
Attempted to install Half-pipe on Rails 4.1, possibly an incompatibility issue, possibly something else.

Installed Half-pipe without version number as the version number caused install to break due to Rails 4.0 dependency. 

Ran generator, however it broke at the requirejs portion. I closed my terminal so I don't have the exact error code sadly. 

It was the npm portion and it required '--force' which I couldn't do. 

This caused an issue with RequireJS in my view, I realized it's possible I need the RequireJS gem, so I installed that and ran bundle install. I had had my rails server running throughout this all(Maybe a mistake on my part?) and was still getting the RequireJs error, so I figured since I added some gems I might need to restart the rails server. Did dos and am now getting 

```
bin/rails:6: warning: already initialized constant APP_PATH
APP_PATH/bin/rails:6: warning: previous definition of APP_PATH was here
```

some additional Googling appears to say that it is related to Spring? I may need to run some sort of Spring command? I'm not 100%. If this is an unrelated issue than I apologize, will close with solution/experience troubleshooting for anyone who experiences similar issues.

**Comment by cranesandcaff** [comment]
Not specifying version was probably the issue. I forked the repo and used that in my Gemfile, removing the Rails dependency. This worked fine, though I did hang up when doing the generator on the same grunt requirejs task.

I will hold off on initiating a pull request because I'm not sure why you specified rails 4.0.0 exactly and I'm not sure if this will break anything. I don't know why it would though. 

If using it with 4.1 breaks anything, would you be interested in the error codes? I ask because you're not supporting 4.1 yet and there is no point in me pointing out bugs in an unsupported version unless you're interested in them.

**Comment by joefiorini** [comment]
Just noticed this issue, sorry for the delay in my reply. I was not aware Rails 4.1 had landed, I haven't actually tried half-pipe with it yet. If you are able to get it working under 4.1 I'm happy to support it and would appreciate any PRs. Thanks!

**Comment by cranesandcaff** [comment]
Hey Joe, no problem on the late reply. I was able to get half-pipe working with 4.1 I'm still working on adding in Gulp scripting. I need to understand the asset pipeline better as I'm still new to Rails. I was able to create a decent generator but it isn't integrated properly into Rails.
