### ISSUE TITLE
Rails 3.2 support

### ISSUE THREAD

**Issue by Bitaru** [half-pipe/half-pipe#78]
Hi,

I just looked on Lower minimum rails requirement #70  issue,  and wanna ask to lower requirement too, i think rails 3.2 still alive, and your gem can make our live simpler. (I mean Front-guys`s live))

**Comment by joefiorini** [comment]
Hey @Bitaru. I'm happy to support Rails 3.2, but we need to reimplement the asset helpers in order to make it work. I don't have any 3.2 apps at the moment, but I'm happy to accept a PR for it if it includes asset helpers.
