### ISSUE TITLE
Would switching to Half Pipe solve this problem?

### ISSUE THREAD

**Issue by frankie-loves-jesus** [half-pipe/half-pipe#79]
Hi,

Trying to simplify my assets management in Rails, especially that of my 3rd party JS (always been a drag to manually update them).

So I found Rails Assets (http://rails-assets.org) but it seems to crumble for Bower packages with a large number of dependencies:

https://github.com/rails-assets/rails-assets/issues/141

Would switching to Half Pipe solve this problem?

**Comment by joefiorini** [comment]
As long as rails assets is your problem and not bower. Half Pipe gives you a straight bower setup. I've never had problems with lots of dependencies, so I think you should be good.

**Comment by frankie-loves-jesus** [comment]
Thanks. Half Pipe here I come!
