### ISSUE TITLE
Error: ENOENT, no such file or directory when running 'rails g half_pipe:install'

### ISSUE THREAD

**Issue by expilo** [half-pipe/half-pipe#81]
I am getting this error when I try to use half-pipe. Here is my Gemfile.

<pre>
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
gem 'half-pipe', '~> 0.3.0.beta'
gem "sass-css-importer", github: "joefiorini/sass-css-importer", branch: "load-paths"
</pre>

I'm getting following message when I try to run: 

rails g half_pipe:install

<pre>
Running "requirejs:public" (requirejs) task
>> Error: ENOENT, no such file or directory
>> '/home/kopszak/tmp/ANGULAR/t008/bower_components/jquery/jquery.js'
>> In module tree:
>>     t008
Warning: RequireJS failed. Use --force to continue.

Aborted due to warnings.
You may now safely migrate your assets to app/scripts and/or app/styles. Feel free to delete app/assets/javascripts and app/assets/stylesheets when you're done.
</pre>

Any idea what could have gone wrong? 

Best

Piotr

**Comment by KingScooty** [comment]
+1 Having exactly the same issue. Is there an easy way to exclude requireJS from the build?

**Comment by scrowland** [comment]
Having the same problem and just realised it was fixed by [this commit](https://github.com/d-i/half-pipe/commit/3d434b37bd3076445782c8c8dc40cde78511c1e7) I think.

With:

```
gem 'half-pipe', :github => "d-i/half-pipe"
```

in my Gemfile, half pipe installed fine!

**Comment by expilo** [comment]
This did the trick for me, indeed. Time to update README.
