### ISSUE TITLE
Compass instead of sass

### ISSUE THREAD

**Issue by turboMaCk** [half-pipe/half-pipe#99]
I thing it will be better to use **compass instead of sass or add this to options for generator**.

I can try to done this if you want.

**Comment by joefiorini** [comment]
My team prefers to use the Sass plugin rather than Compass. If you want to send a PR for it that's fine, but it's probably not something I'll get to.

**Comment by turboMaCk** [comment]
The reason for this is that **yoeman** generators are using compass instead of sass so it could be helpful feature for porting for somebody.
